liquibase:
  enabled: false

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://$$$$:3306/quartz
    username: root
    password: 1234